// <auto-generated />
using System;
using Fiap.Aula05.Web.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fiap.Aula05.Web.Migrations
{
    [DbContext(typeof(DimDimContext))]
    [Migration("20221021005827_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fiap.Aula05.Web.Models.Corretora", b =>
                {
                    b.Property<int>("CorretoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorretoraId"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CorretoraId");

                    b.ToTable("Corretoras");
                });

            modelBuilder.Entity("Fiap.Aula05.Web.Models.Investimento", b =>
                {
                    b.Property<int>("InvestimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestimentoId"), 1L, 1);

                    b.Property<decimal>("CapitalInvestido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CorretoraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rendimento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatusInvestimentoId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("TipoInvestimento");

                    b.HasKey("InvestimentoId");

                    b.HasIndex("CorretoraId");

                    b.HasIndex("StatusInvestimentoId");

                    b.ToTable("Tbl_Investimento");
                });

            modelBuilder.Entity("Fiap.Aula05.Web.Models.InvestimentoObjetivo", b =>
                {
                    b.Property<int>("ObjetivoId")
                        .HasColumnType("int");

                    b.Property<int>("InvestimentoId")
                        .HasColumnType("int");

                    b.HasKey("ObjetivoId", "InvestimentoId");

                    b.HasIndex("InvestimentoId");

                    b.ToTable("InvestimentosObjetivos");
                });

            modelBuilder.Entity("Fiap.Aula05.Web.Models.Objetivo", b =>
                {
                    b.Property<int>("ObjetivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjetivoId"), 1L, 1);

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObjetivoId");

                    b.ToTable("Objetivos");
                });

            modelBuilder.Entity("Fiap.Aula05.Web.Models.StatusInvestimento", b =>
                {
                    b.Property<int>("StatusInvestimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusInvestimentoId"), 1L, 1);

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("StatusInvestimentoId");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Fiap.Aula05.Web.Models.Investimento", b =>
                {
                    b.HasOne("Fiap.Aula05.Web.Models.Corretora", "Corretora")
                        .WithMany("Investimentos")
                        .HasForeignKey("CorretoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Aula05.Web.Models.StatusInvestimento", "StatusInvestimento")
                        .WithMany()
                        .HasForeignKey("StatusInvestimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corretora");

                    b.Navigation("StatusInvestimento");
                });

            modelBuilder.Entity("Fiap.Aula05.Web.Models.InvestimentoObjetivo", b =>
                {
                    b.HasOne("Fiap.Aula05.Web.Models.Investimento", "Investimento")
                        .WithMany("InvestimentosObjetivos")
                        .HasForeignKey("InvestimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fiap.Aula05.Web.Models.Objetivo", "Objetivo")
                        .WithMany("InvestimentosObjetivos")
                        .HasForeignKey("ObjetivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investimento");

                    b.Navigation("Objetivo");
                });

            modelBuilder.Entity("Fiap.Aula05.Web.Models.Corretora", b =>
                {
                    b.Navigation("Investimentos");
                });

            modelBuilder.Entity("Fiap.Aula05.Web.Models.Investimento", b =>
                {
                    b.Navigation("InvestimentosObjetivos");
                });

            modelBuilder.Entity("Fiap.Aula05.Web.Models.Objetivo", b =>
                {
                    b.Navigation("InvestimentosObjetivos");
                });
#pragma warning restore 612, 618
        }
    }
}
